name: Fix Code Style

on:
  push:

jobs:
  fix-style:
    name: Fix Code Style
    timeout-minutes: 15
    runs-on: ubuntu-20.04
    env:
      COMPOSER_NO_INTERACTION: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.0
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-progress

      - run: composer fix-style
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: composer fix-style
          commit_author: laravel-ide-helper <laravel-ide-helper@users.noreply.github.com>
